# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Inversiones Ilego
email: inversionesilego@gmai.com
description: > # this means to ignore newlines until "baseurl:"
  PRODUCTOS P.O.P Y SERVICIOS DE ESTAMPADO ILEGO C.A.
  R.I.F. J-40415588-0.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: IDANALET
facebook_username:  Ipresos Ilego
istagram_username: inversionesilego
# Build settings
markdown: kramdown
